### ISSUE TITLE
[ENH] Add shortcuts

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#103]
Implement the following shortcuts in the tool for users to have easy access to

- [x] #117
- [x] Feedback shortcut to GitHub issues of the repo
- [x] Website shortcut
- [x] Repo shortcut
- [x] Documentation shortcut

**Comment by surchs** [comment]
Also rebrand the tools to have "Neurobagel" as part of their tool name?

**Comment by rmanaem** [comment]
Let's discuss it here https://github.com/neurobagel/project/issues/136
