### ISSUE TITLE
[BUG]: Dropdown options overflows container

### ISSUE THREAD

**Issue by joshunrau** [neurobagel/old-query-tool#106]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

The dropdown options will look nice for all items, regardless of how long the option is

### Current Behavior

<img width="478" alt="Screenshot 2023-06-08 at 7 23 14 PM" src="https://github.com/neurobagel/query-tool/assets/78170036/a4a05c93-939f-486d-86b8-f95b231d8d6c">

### Environment

- OS:
- Python/Node version:

### How to reproduce

Use iPhone SE in browser dev tools then toggle the dropdown for diagnosis

**Comment by joshunrau** [comment]
In addition, on hover the option is truncated. 

<img width="272" alt="Screenshot 2023-06-08 at 7 33 56 PM" src="https://github.com/neurobagel/query-tool/assets/78170036/1b8b508f-11ca-4bbb-be28-bddaf878e598">

**Comment by MIZwally** [comment]
Additional dropdown issue; the dropdown extends past the bottom of the page for the Assessment and Imaging options.
<img width="297" alt="Screenshot 2023-07-20 at 1 11 57 PM" src="https://github.com/neurobagel/query-tool/assets/132242817/861be0db-60b7-4ae1-973a-0bedc2dae125">
<img width="297" alt="Screenshot 2023-07-20 at 1 12 38 PM" src="https://github.com/neurobagel/query-tool/assets/132242817/47df9b0d-46c0-4982-83ab-1792a39ccaf8">

**Comment by surchs** [comment]
I think this has been implicitly addressed by the app refactor. Closing
