### ISSUE TITLE
Sketch the design of the navbar

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#117]
Create a sketch for the proposed design of the navbar of the query tool based on shortcuts mentioned in #103 
See [Bootstrap-vue](https://bootstrap-vue.org/) as inspiration

**Comment by rmanaem** [comment]
@neurobagel/dev What do you think?

![Image](https://github.com/neurobagel/query-tool/assets/77515879/0799abd8-bffc-454e-aad5-5c8fa85ae2d6)

**Comment by surchs** [comment]
I think that looks absolutely awesome @rmanaem! I'm for it

**Comment by surchs** [comment]
@rmanaem I think we can have this issue in review now, wdyt?

**Comment by alyssadai** [comment]
Ou, I love the idea of the dropdown with different options for feedback!

I'm still slightly attached to the idea of having some kind of indicator of what "stage" of the Neurobagel workflow folks are on (annotate, query, etc.). Since we won't include the tool name in the navbar, what do we think of adding a descriptive title to the page similar to [OpenNeuro's search interface](https://openneuro.org/search?query={%22keywords%22:[]}), maybe with something like "Search across Neurobagel-annotated datasets" or something similar? :)

Could of course be a separate issue.

**Comment by rmanaem** [comment]
> what do we think of adding a descriptive title

Like in the tab title?
I like the idea of having the tool mentioned, so how about a `tools/services` shortcut that has a dropdown similar to the feedback shortcut.

**Comment by alyssadai** [comment]
Not a lab title, but a title on each tool page that summarizes the tool's purpose.

So for example, if a person heads directly to `query.neurobagel.org`, they don't just see the query fields, but also a title on the page that says e.g. "Search across Neurobagel-annotated datasets", so they know what it is they're actually doing when they fill out the query form. Similarly, for the annotation tool, the title could say "Generate harmonized phenotypic annotations of dataset" or something.

**Comment by surchs** [comment]
@rmanaem could you update your proposal based on the feedback (or explain why you disagree) and then close this issue please?

**Comment by rmanaem** [comment]
@alyssadai Is this what you had in mind (font size to be adjusted)?

![Image](https://github.com/neurobagel/query-tool/assets/77515879/c989eb58-2d49-4617-ad52-cebf2f3d1a37)

**Comment by alyssadai** [comment]
Yep, that looks fine to me, though I would suggest making the title more generic, since the API may not always (?) be pointing to just OpenNeuro data. So, `"Search Neurobagel-annotated datasets"` or `"Search datasets in the Neurobagel graph"` or something similar, maybe? @surchs not sure if you have an opinion on this.

I would also be open to keeping the "Query fields" subtitle you had before in there, and just having the title above the form and results, like below (excuse my much uglier sketch):

![Image](https://github.com/neurobagel/query-tool/assets/65699389/b0c7ca6a-955f-48f0-b060-0869aa4c055d)

**Comment by surchs** [comment]
I think both would be nice:

- a generic title that isn't tied to openneuro (for when we make deployments that show other data)
- a disclaimer that we're showing openneuro data (for the openneuro deployment)

how about this (edit link here: https://miro.com/app/board/uXjVM_-7srw=/?share_link_id=123467386353)
![Query Tool Navbar - Frame 1](https://github.com/neurobagel/query-tool/assets/1302022/06279998-4865-45b9-a336-e7d6f4d0879a)

**Comment by alyssadai** [comment]
@surchs, do you think the informative title should be part of the navbar or on the page itself? I thought the navbar would have a link to each tool (or a dropdown that lists them), with simple one-word names "annotator", "query", etc. And then once you click on one of those, you navigate to the relevant tool page with the informative title on the page itself.

Thoughts?

**Comment by surchs** [comment]
I was thinking that the title would be part of the nav bar. I think that's the part I'm visually drawn to to look for "Where am I and what is this". If we keep it consistent across apps then even more so.

**Comment by jarmoza** [comment]
Here are my suggestions:

1. Keep the logo and tool name (Annotate, Query) on the left of the navbar. 
2. Put the version next to the tool name on the left of the navbar
3. Move 'Docs' and 'Feedback' together with the GitHub link on the right of the navbar (and maybe change it to Documentation - just to be more formal)

So -

`<logo> <title> <version>                     Documentation Feedback <gh logo/link>`

**Comment by rmanaem** [comment]
Thanks for the feedback folks!
I like the proposed changes by @jarmoza. @alyssadai, and @surchs do you concur?

**Comment by alyssadai** [comment]
Looks good to me!

**Comment by rmanaem** [comment]
I'd like to propose a change to the agreed-upon design of the navbar 

> `<logo> <title> <version>                     Documentation Feedback <gh logo/link>`

Since we don't have a logo at the moment we can stick with the tool name for now. So this is what I have in mind:

` <tool name>                    <version> Documentation Feedback <gh logo/link>`

- Documentation links to Neurobagel docs
- Feedback links to the tool issues on GitHub
- Version will link to the tag on GitHub

What do you all think?

**Comment by surchs** [comment]
I think the tool name should have something like "search cohorts at the sample level", either as part of the name, or in the form of `"<tool name>: Search ..."` to make sure what we add on top of OpenNeuro. We might even consider pointing out that all of this is currently openneuro

**Comment by rmanaem** [comment]
@surchs Not sure I'm following. Mind elaborating on this screen shot?

![Screenshot from 2023-07-10 15-57-23](https://github.com/neurobagel/query-tool/assets/77515879/b61a5557-e371-4fbd-8797-e60fbb440a81)

**Comment by surchs** [comment]
![Query Tool Navbar - Frame 2](https://github.com/neurobagel/query-tool/assets/1302022/5d63772c-15a3-4d35-ae7c-145edc763828)

edit: I think adding a tagline like above ("define and find cohorts at the sample level") is helpful to differentiate our tool from what already exists

**Comment by rmanaem** [comment]
![Screenshot from 2023-07-10 16-13-15](https://github.com/neurobagel/query-tool/assets/77515879/4573166e-5273-44cb-94ab-ab0737944c2a)

**Comment by surchs** [comment]
any chance we can set a color for the `"Neurobagel Query"` part of the string?

**Comment by rmanaem** [comment]
Yea, what color do you have in mind?

**Comment by surchs** [comment]
Maybe the purple from the poster? We could also reuse it on the website. @alyssadai do you have an exact color match that could work? If not, let's just bold the `Neurobagel Query` part for now and figure out our "color" later

**Comment by jarmoza** [comment]
@rmanaem, @surchs In looking this subtitle over, not a fan of the current formatting.

1. The "Neurobagel" part makes sense as a placeholder for the logo, but
2. The subtitle makes the space/title feel cluttered.

I think the subtitle should be smaller and beneath the title.

This looks bad:
![Screen Shot 2023-07-10 at 6 03 39 PM](https://github.com/neurobagel/query-tool/assets/4140162/e9f63de6-c2b0-481d-9cb0-196419cb417b)


This would be preferable: 
![Screen Shot 2023-07-10 at 6 03 39 PM copy](https://github.com/neurobagel/query-tool/assets/4140162/6450aa16-e2f7-4ef5-8d61-e80437184668)

**Comment by surchs** [comment]
I understand what you mean, but I think it'd be clearer if you could update it with the query tool screenshot.

**Comment by jarmoza** [comment]
Updated my comment with query tool screenshots

**Comment by jarmoza** [comment]
@rmanaem Any feedback on my proposed change for the title/subtitle above?

**Comment by rmanaem** [comment]
Looks good to me

**Comment by alyssadai** [comment]
Sorry for the late reply! Here are the colours from the poster @rmanaem:

Dark purple: `#470A68`
Light purple: `#E5E1E6`
Neuro teal (if needed): `#2CCCD3`

**Comment by rmanaem** [comment]
Is it just me or it's hard to tell the subtitle is Dark purple

![Screenshot from 2023-07-11 12-49-59](https://github.com/neurobagel/query-tool/assets/77515879/52e96acb-2eb3-499b-9493-b3916cb78c4a)

**Comment by alyssadai** [comment]
I can tell it's purple!

**Comment by rmanaem** [comment]
Final product

![Screenshot from 2023-07-11 13-11-46](https://github.com/neurobagel/query-tool/assets/77515879/4b9134b9-3efd-47e8-a2fc-be50adc0fb0b)
