### ISSUE TITLE
Make requirement of selecting datasets for download more apparent

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/old-query-tool#128]
(Echoing some existing feedback)

UX details: took me a while to find the `Select all datasets` tickbox to "enable" the download button.
Maybe bring the tick box closer to the download button.

When users then tick this box and all datasets get selected they should then realize that they can toggle datasets individually.

_Originally posted by @Remi-Gau in https://github.com/neurobagel/query-tool/issues/93#issuecomment-1570587515_

Alternatively, we could maybe have some text reading "Please select at least one dataset" next to download button when none have been selected?

**Comment by jacobsanz97** [comment]
I also found it unintuitive to have to select the datasets I want to download after querying. Maybe you could add a little text box on top of the 'download' buttons that specifies we have to select the checkboxes in order to download?
