### ISSUE TITLE
Make first release

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#129]
we want to release the query tool, so that we can mint a citable DOI for it.

Steps:

- [x] Pick a semver version (see below discussion, if in doubt, let's go with 0.1.0)
- [x] Follow [these descriptions](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) so Zenodo can mint a DOI for our release of the API
- [x] add a citation.cff files + validation workflow with basic metadata
  - see: https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md
- [x] enable tracking of the repository by Zenodo **before** making a release
- [x] make a release on github (see https://github.com/neurobagel/documentation/wiki/Release-process)
  - stick to basic description of features
- [x] confirm that a DOI has been minted and dereferences to our codebase

**Comment by surchs** [comment]
Because this is something we need to do in support of a grant application, we'll have to move rather quickly here. The plan is to make a release today.

**Comment by surchs** [comment]
I'll make a release as version 0.1.0

**Comment by surchs** [comment]
For reviewer: here is the release draft: https://github.com/neurobagel/query-tool/releases

**Comment by alyssadai** [comment]
@surchs, the description looks good but dependabot-related changes currently make up 1/3 of the points under "What's new" - worth removing?

**Comment by surchs** [comment]
oh right. I don't think I edited the changelog at all. Will do now

**Comment by surchs** [comment]
:eyes: 
mine look like this

![image](https://github.com/neurobagel/query-tool/assets/1302022/03333b13-2ddf-433b-b576-b29d663e1580)
