### ISSUE TITLE
Datasets do not get removed from `downloads` array when new query is run

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#134]
Once a dataset from the results is selected it is added to the `downloads` array and the only way to remove it from the `downloads` is to unselect it (uncheck the checkbox).
So when a query is run and dataset X from the results is selected (therefore added to the `downloads` array) but not unselected (not removed from the `downloads`) before running another query which may or may not include dataset X in the returned results, X is still included in the `downloads` array.

**Comment by surchs** [comment]
@rmanaem how about `"Datasets do not get removed from DownloadsArray when new query is run"` or something like that as the issue title?
