### ISSUE TITLE
Make two buttons for dataset- and participant-level results

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#141]
_Originally posted by @michellewang in https://github.com/neurobagel/query-tool/issues/93#issuecomment-1612209914_:

> I didn’t realize until someone pointed it out yesterday that we could toggle between dataset-level and participant-level results. Personally, I think it would be better to have 2 download buttons instead of the “Toggle level of detail to download” checkbox

To resolve:

- [x] have one permanently visible button `"Download dataset results"`. Clicking it will download the dataset-level.csv
- [x] have one permanently visible button `"Download participant results"`. Clicking it will download the participant-level.csv
- [x] Both buttons should become enabled and disabled in the same way the current download button does (e.g. disabled unless at least one dataset is selected)
-  ~If button text is too large, we can have a linebreak in there (i.e. make button bigger)~
- [x] Update README.md
- [x] Update related tests

**Comment by rmanaem** [comment]
@surchs @jarmoza Do you have any thoughts on the placement of the buttons in the UI, one stacked on top of the other or next to each other?

**Comment by jarmoza** [comment]
I think side by side.
