### ISSUE TITLE
Refactor the `DownloadResultsButtton` component

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#146]
Currently the `DownloadResultsButton` component houses two `b-button` elements one for participant-level results and one for dataset-level results.
Refactor the component to a generic one button component that receives its data from the parent through props.

**Comment by surchs** [comment]
What do you have in mind with this one @rmanaem? Is this something that affects the UI or is this just a refactor internally?

**Comment by rmanaem** [comment]
It's just a refactor internally.

**Comment by surchs** [comment]
ok, let's change the labels then to be clear.
