### ISSUE TITLE
[BUG] Dataset and Participant .tsv downloads have `\n` when downloaded from Chrome, but not Firefox

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#151]
When I
- run a query
- select datasets
- click the participant or dataset download button, 

then I expect:
### Expected Behavior

To get a `.tsv` that starts with a header row, e.g.: 

```tsv
DatasetID	SubjectID	Age	Sex	...
http://neurobagel.org/vocab/0143b0cc...	sub-s102	19.0	http://purl.bioontology.org/ontology/SNOMEDCT/248153007
```

### Current Behavior
But instead I get:
```tsv
\n
      DatasetID	SubjectID	Age	Sex	...
http://neurobagel.org/vocab/0143b0cc...	sub-s102	19.0	http://purl.bioontology.org/ontology/SNOMEDCT/248153007
```

### How to reproduce

- use the query app with Chrome (e.g. `114.0.5735.198`)

### Anything else?

- if you use query app with Firefox (e.g. `115.0`), there is no newline character in the .tsv :shrug: 

Whatever the cause of the bug is, we need to:

- [ ] write a test that fails when there is a newline at the top of the `.tsv`
- [ ] enable cross-browser testing (at least for cypress) or at least make sure tests are run on Chrome (as sad as it is, most people are on Chrome)

**Comment by Remi-Gau** [comment]
Note that the first column is not `DatasetID` but is `      DatasetID` with some space padding.

Tiny thing but will make downstream users to not have to deal with this. :-p
