### ISSUE TITLE
Feedback button overlaps with download buttons

### ISSUE THREAD

**Issue by MIZwally** [neurobagel/old-query-tool#162]
Upon the generation of results, the download options are covered up by the feedback button, and you can't scroll down further to move the feedback button.

**Comment by surchs** [comment]
hey @rmanaem. afaik feeback position is being set inside appzi. Is that how you are planning on addressing this? 

edit: should be a pretty trivial fix from there

**Comment by rmanaem** [comment]
@surchs Yea It's either that or moving the download buttons to the left,
I moved the feedback to the bottom left the other day but I feel like it reduces visibility wdyt?

**Comment by surchs** [comment]
if you have a draft PR, it'd be easier to look at it with the preview deploy. But overall: up to you. I think the feedback button could live on the right edge and be out of the way there

**Comment by surchs** [comment]
Looks good @rmanaem. Since there is no PR, please in the future mention what makes this done or what a reviewer should look at.
