### ISSUE TITLE
[ENH] Allow selection of multiple options in dropdown menus

### ISSUE THREAD

**Issue by MIZwally** [neurobagel/old-query-tool#164]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### New feature

Currently you are only able to select one option for the filters that contain dropdown menus. What if you're looking for a study where participants have multiple diagnoses, or are open to multiple assessments or imaging techniques? Making it possible to select more than one option to filter by would remove this issue.

**Comment by rmanaem** [comment]
Thanks @MIZwally for the feedback!
This issue appears to be a duplicate of neurobagel/query-tool#67.  Please follow the discussion there. Closing this issue.
