### ISSUE TITLE
Code snippet on UI on how to download data

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#173]
As a query user, having run my query, I want to be shown a piece of code I can copy/paste (single command ideally) that I can run so that my selected cohort results appear on my disk.

This is only about the UI element, we can figure out what the code is separately.
@rmanaem

**Comment by rmanaem** [comment]
The code 
```
docker run -t -v $(pwd):/data neurobagel/dataget:latest /data/dataset-results.tsv /data/participant-results.tsv /data/output
```

**Comment by surchs** [comment]
Steps user needs to do before the `docker` call:

1. Select a bunch of datasets (maybe not need to display this if the modal button only becomes visible once they have selected something)
2. Download the two files to some directory on their machine
3. `cd` into the directory where they downloaded the two files
4. Reflect on what the output directory should be called, atm it is `/data/output`

**Comment by rmanaem** [comment]
@surchs what do you think?

<p>Please follow these steps:</p>
            <ol>
              <li>Select at least one dataset</li>
              <li>Download the participant-level and dataset-level results</li>
              <li>Change directory to the location of the downloaded files</li>
              <li>Copy and run the following command:</li>
            </ol>
            <code>docker run -t -v $(pwd):/data neurobagel/dataget:latest /data/dataset-results.tsv /data/participant-results.tsv /data/output</code>

**Comment by surchs** [comment]
@rmanaem what's your take on the cypress issue so far? Should we go and ask them for advice? Or is there a way to get around that? Would be good to describe the issue you are experiencing so we can reference it again in the future

**Comment by alyssadai** [comment]
Will finish with PR once @rmanaem is back.

**Comment by surchs** [comment]
Unblocking this and taking over completion of the PR, mainly so we can have this feature for when Eric is trying the tool out at the end of the week.
