### ISSUE TITLE
Modal not visible in Cypress

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#184]
During the implementation of #173 we discovered that while the modal related elements (a series of `divs`) are present in the DOM and the backdrop of the modal can be seen, the modal itself is not visible in cypress testing window.

![Screenshot from 2023-08-16 16-35-36](https://github.com/neurobagel/query-tool/assets/77515879/a0f4247b-fd98-4298-ac30-ffd065b2cc64)

To replicate:

`ResultsContainer.vue`
```
<b-button
  class="nb-button"
  @click="$bvModal.show('example-usage-modal')"
  data-cy="example-usage-button"
>
  Example usage
</b-button>
<b-modal
  id="example-usage-modal"
  title="Example usage"
  hide-header-close
  hide-footer
  centered
  size="xl"
  data-cy="example-usage-modal"
>
  <p>Please follow these steps</p>
  <ol>
    <li>Select at least one dataset</li>
    <li>Download the participant-level and dataset-level results</li>
    <li>Change directory to the location of the downloaded files</li>
    <li>Copy and run the following command:</li>
  </ol>
  <code class="code">{{ code }}</code>
</b-modal>
```

`ResultsContainer.cy.js`
```
cy.get('[data-cy="example-usage-button"]').should('be.visible').click();
cy.get('[data-cy="example-usage-modal"]').should('be.visible');
```

**Comment by surchs** [comment]
I think we're not using any modals at the moment. I'd say we close this issue, @rmanaem ?

**Comment by surchs** [comment]
Closing because of refactor
