### ISSUE TITLE
Expose query variables with UI elements

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#2]
The UI should expose the same variables with UI elements (sliders, dropdowns, etc) that the API is exposing ([see here](https://github.com/neurobagel/bagelapi/issues/31)).

- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
  - e.g. whether a participant is a control subject or not (as implemented in the API)

Each of these should:
- Implement the UI element as a vue component
- Display the component in the QueryFrom.vue component
- Connect the element to an (asynchronous) API request
- Test the implementation with a component test
- have a short line added to the README about what the UI element queries (like an early draft of user docs)
  - e.g.: `age: select the minimal and/or maximal age (in years) of a participant that should still be included in the results`
- provide options for sex, diagnosis, imaging modality, assessment tools

**Comment by surchs** [comment]
I think this is also a bigger chunk than a single issue. I'd say we split each of these points up into their own issue. Each of them will need to be hooked up to an API request, and we want to make sure that the API request goes out as expected with an integration test. So let's do a bunch of small PRs here, rather than one big pile of stuff at once.

**Comment by rmanaem** [comment]
@surchs 
Could you elaborate on what you had in mind here?
>have a short line added to the README about what the UI element queries (like an early draft of user docs)

**Comment by surchs** [comment]
I was just thinking of a section in the README that explains what each Query paramter does, maybe preceded by a screenshot of the interface. Something like:

> To define a cohort, define you inclusion criteria using the following UI elements on the left:
age: select the minimal and/or maximal age (in years) of a participant that should still be included in the results
...

I added the example to the issue description  above as well

**Comment by rmanaem** [comment]
See #26 for integration test

**Comment by rmanaem** [comment]
@surchs 
Do you happen to know the options for the following fields?
- diagnosis
- imaging modality
- assessment tool
- subject group
   - I think for this it's control and treatment/experimental

**Comment by surchs** [comment]
I got these with the following query:

```sparql
PREFIX bg: <http://neurobagel.org/vocab/>
PREFIX snomed: <http://neurobagel.org/snomed/>
PREFIX nidm: <http://purl.org/nidash/nidm#>

SELECT DISTINCT ?diagnosis ?assessment ?imaging
WHERE {
    ?subject bg:hasSession ?session;
             bg:assessment ?assessment;
             bg:diagnosis ?diagnosis.
    ?session bg:hasAcquisition/bg:hasContrastType ?imaging.
}
```
[Untitled-1_sparql_results.csv](https://github.com/neurobagel/query-tool/files/10549651/Untitled-1_sparql_results.csv)

**Comment by rmanaem** [comment]
I'm guessing these options need to be updated once the data for the first release has been added to the graph.

**Comment by surchs** [comment]
Yes, that's correct. I don't expect us to have this hard-coded for more than a couple of PRs though / until the API has a "show me what is available" endpoint (https://github.com/neurobagel/bagelapi/issues/37). 

In the meantime I'd say we just add the values that we know are in the graph to keep the number of choices a bit more manageable.

**Comment by rmanaem** [comment]
I thought we pushed that to the next release of the API.

**Comment by surchs** [comment]
Yes, to clarify: we will have the options hardcoded for this release. In a (near) future release, we will replace the hard-coded options with a dynamic query to the yet-to-be-created API endpoint that will return the list of accessible options.

**Comment by rmanaem** [comment]
Update:
`CategoricalField.vue` component is defined and implemented as a generic component to be used for implementation of UI for the following fields:
- sex
- diagnosis
- imaging modality
- assessment tools
- subject group
