### ISSUE TITLE
CI isn't running on merge to main

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#203]
We just merged https://github.com/neurobagel/query-tool/pull/199 with a failed linter check (not sure how tbh, we have branch protection on). Obviously linter check isn't breaking things - so no major harm done. But the main branch remained green after this. This made me realize that we aren't running **any** checks on push/merge to the main branch here - we only run the deployment. 

That's no good. If instead of a linter we had ignored a failed test then main should not be looking green anymore (and we also shouldn't deploy). If you break main, you need to know this (and then fix it right away). 

I think all tests **have to** run on main, but the linter **should** run because why not. 

We should then also confirm that if for some reason we push broken stuff to main and the tests fail, that we don't deploy!

**Comment by rmanaem** [comment]
To resolve this we'll update the workflows to also trigger on push to `main` branch.
