### ISSUE TITLE
Build docker image from clean context

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#211]
- Ensure the ci build process for the public docker image starts from a clean context (e.g. separate job)

Right now we build the docker image in the same job that we deploy the static site to GH pages from: https://github.com/neurobagel/query-tool/blob/8cdc5f2a2e62d8b98f352807f253b9c22fe03cf8/.github/workflows/cd.yaml#L37-L52

That's no good, because the `.env` file from the static site build gets baked into our public Docker image - and we don't want that. We will fix this in https://github.com/neurobagel/query-tool/issues/210. But we also should also make sure that we use a fresh context to build the image. Either by building in a separate workflow, or at least a separate job.

_Originally posted by @surchs in https://github.com/neurobagel/api/pull/154#discussion_r1316470086_

**Comment by alyssadai** [comment]
We will split these into two workflow files, maybe one `build` and one `deploy`
