### ISSUE TITLE
Add note to use https protocol when sending requests to `api.neurobagel.org`

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/old-query-tool#216]
If a user accidentally (🤡) sets `API_QUERY_URL` to `http://api.neurobagel.org/` instead of `https://api.neurobagel.org/` for a locally deployed query tool, they will get a CORS error even if the remote API is allowing all origins which is confusing to troubleshoot (or at least, the problem is not immediately obvious).

This is expected due to how NGINX is currently set up on the server: the API should only listen to https requests.

To avoid confusion, we should make it extra obvious in the README that if the user wants to use the remote API, they should use `https` and not `http`.

**Comment by surchs** [comment]
Thanks for addressing this so quickly @alyssadai. Agree that the new note will help! But I don't think this should lead to CORS issues. I would expect that if you don't get past NGINX then you either get nothing or something with an error message. Can you confirm that this is a CORS issue?

**Comment by alyssadai** [comment]
@surchs, I don't think the problem should originate from CORS since the public API is allowing all origins from what I can tell, but when `http` is used instead of `https` it _appears_ like a CORS problem which is possibly misleading (?)

See screenshots below for what I mean.

<img width="463" alt="http_console_result" src="https://github.com/neurobagel/query-tool/assets/65699389/c19b65f7-263c-4403-ad88-543c9225725f">
<img width="461" alt="http_console_result2" src="https://github.com/neurobagel/query-tool/assets/65699389/3c41e53e-1986-426a-a901-c5145d23bb80">
<img width="461" alt="http_network_result1" src="https://github.com/neurobagel/query-tool/assets/65699389/ce53b691-2861-40e2-b0a0-100653b60f47">

I'm not actually sure why it shows up as a CORS error. That said, when I was troubleshooting our deployment instructions with Thomas last week, we also ran into a few cases where a query tool error that looked to be CORS-related in the browser ended up not having to do (at least not obviously) with the allowed origins.

**Comment by alyssadai** [comment]
Related to #217

**Comment by alyssadai** [comment]
Documented this behaviour and how to troubleshoot query tool errors more generally [here](https://github.com/neurobagel/documentation/wiki/Query-Tool#troubleshooting-the-query-tool). This issue is now closed by #217
