### ISSUE TITLE
Handling possible server-side errors

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#25]
Given the implementation `submitQuery` function in `QueryForm.vue` component, how should server-side errors thrown by our API e.g., [`min_age > max_age` ](https://github.com/neurobagel/bagelapi/blob/fc48a2c2b53bd1907b9825505024a93b9f6ec4f3/app/api/models.py#L22-#L39) be handled?

**Comment by surchs** [comment]
Hey @rmanaem , can you explain a little more what about the error handling related to the server side? Do you mean server side rendering?

**Comment by rmanaem** [comment]
@surchs Below is the current implementation of `submitQuery`, basically I'm curious to hear your thoughts on what should go in the catch block.

```
async submitQuery() {
      const url = process.env.API_QUERY_URL;
      try {
        const resp = await this.$axios.get(url);
        this.results = resp.data;
      } catch (err) {
        // TODO Handle situations that may throw an error e.g., when min age > max age
        // could emit an event here and show an "error view" in results or use vuelidate
        // to validate the form before submission
      }
    }
```

**Comment by surchs** [comment]
I think mid-term your app should not let me make silly requests - i.e. in your example, if I make min_age > max_age, that should result in the UI complaining to me and not let me send a request in the first place. But in the meantime, I would rely on the API to tell you that something dumb was asked. 

So I think the cases you should handle here is:
- request got no response (server down?) -> say server not reached
- request got response with error/ not.OK.status (bad request?) -> say server didn't like the query (or something like it)
- request got empty response (no results) -> say "no results" or something like it
- and then your catchall with `catch` for anything we didn't think of

That should cover it, no?

**Comment by rmanaem** [comment]
Update:

- Request got no result -> show "no result view"
- Request with error [coming from Neurobagel API](https://github.com/neurobagel/api/blob/1a0487ff9665506a71e17d1d7b131cef0f385581/app/api/models.py#L21-L49) -> handled using `validateQueryForm` see #28 
- server down and all other server-side errors will be caught by `catch` -> display `Oops something went wrong` text aka error  view

**Comment by surchs** [comment]
Nice, sounds very good. Do these updates refer to an upcoming PR?

**Comment by rmanaem** [comment]
Yea right after #44
