### ISSUE TITLE
Switch to requesting available terms for queryable variables from linked API(s)

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/old-query-tool#261]
Now that https://github.com/neurobagel/federation-api/issues/12 is done, the f-API has an endpoint to get available terms from all available n-APIs.

We should now

- [x] Fetch the available terms for diagnosis and assessment tool from the new f-API endpoint
- [x] Decide at what stage of the lifecycle we should make the request
- [x] Remove the old hardcoded diagnosis and assessment options.
- [x] Provide a nice error message (e.g. https://bootstrap-vue.org/docs/components/toast) if either or both of these requests fail and we get zero terms back from the f-API

**Comment by surchs** [comment]
comes after https://github.com/neurobagel/federation-api/issues/12

**Comment by surchs** [comment]
@rmanaem mind taking a look and seeing if there is anything else to be added

**Comment by rmanaem** [comment]
Looks good to go. 
We can start working on it once https://github.com/neurobagel/api/issues/211 is done.

**Comment by rmanaem** [comment]
Blocked by #305
