### ISSUE TITLE
Update hardcoded assessment and diagnosis options

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/old-query-tool#262]

**Comment by surchs** [comment]
This issue and the linked PR will be replaced by https://github.com/neurobagel/federation-api/issues/12 and then be closed together with it.

**Comment by alyssadai** [comment]
@surchs, wdyt about closing this issue as not planned and instead moving this one into tracked? https://github.com/neurobagel/query-tool/issues/261

**Comment by surchs** [comment]
Ah, yeah, that's a better idea. In that case @rmanaem should make a decision whether he wants to close the PR linked to #261 also. Arman: could you close this issue as not planned after you decide on the PR (keep the branch for now).

**Comment by rmanaem** [comment]
I mean we could just merge the PR and close this issue along with it since its already done.

**Comment by surchs** [comment]
And then remove it again once https://github.com/neurobagel/federation-api/issues/12 comes in? Sure, that also works

**Comment by rmanaem** [comment]
Yea something has to be removed either way.
