### ISSUE TITLE
Allow for querying specifc nodes 

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#267]
For OpenNeuro we need to have a way to only query OpenNeuro data. But when we do that, users should also see that there are other node APIs they could also query by making a manual selection.

TODO:
- [x] Implement a UI element (e.g., dropdown) and required logic to allow users to query a specific node from the available nodes in the federation api
- [x] Have the label be "Neurobagel graph database" or similar

**Comment by surchs** [comment]
**Option 1**:

everything starts out selected looking like this
![image](https://github.com/neurobagel/query-tool/assets/1302022/89ba19f4-88e0-4402-a8d8-13d9d029bcd3)

**Option 2**: 

everything starts out selected looking like this
![image](https://github.com/neurobagel/query-tool/assets/1302022/42da5206-455e-4c1f-a8a1-9d1e8b4e1602)
