### ISSUE TITLE
Add visual indicator of "beta"

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#293]
When I open the query tool, I want to 

- [x] see a clear visual indicator that the tool is in "beta" / active development, 
- [x] with a link to docs

See e.g. https://bootstrap-vue.org/docs/components/badge

**Comment by rmanaem** [comment]
> with a link to a document (docs / GH issue, ...) that lists known limitations and development goals

@neurobagel/dev Do we have a page in docs that outlines the above?
