### ISSUE TITLE
Add OpenNeuro specific note on limitations

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#294]
When I select "OpenNeuro" as a query node (#267) a dedicated visual element appears prominently on the query tool and 

- [x] explains that OpenNeuro search is being tested / developed
- [x] explains that we don't cover all of the OpenNeuro datasets
- [x] provides a link to a site where I can learn more, and help annotate more data (https://github.com/neurobagel/planning/issues/77)

**Comment by rmanaem** [comment]
I think https://bootstrap-vue.org/docs/components/alert is a good option for the UI element

**Comment by surchs** [comment]
Need some text to add in the alert

**Comment by surchs** [comment]
Suggestion for the text:

> The OpenNeuro node is being actively annotated at the participant level and does not include all datasets yet. Check back soon to find more data. If you would like to contribute annotations for existing OpenNeuro datasets, please get in touch at https://github.com/OpenNeuroDatasets-JSONLD/.github/issues.
