### ISSUE TITLE
pre-populate valid query parameter choices

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#3]
For this first release, we will hard-code the choices for categorical variables like diagnosis and imaging modality into the app. That is, in order to know what options a user should have in a UI element to select "diagnosis", we will rely on some internal, hardcoded variable. A good starting point could be to check what unique options are actually available in our graph (although that may change).

We need to code the options for:

- [ ] provide options for sex
- [ ] provide options for diagnosis
- [ ] provide options for imaging modality
- [ ] provide options for assessment tool

**Comment by rmanaem** [comment]
I think we could have the implementation of options for each categorical variable as a sub-task inside their own issues when implementing them with UI elements in #2 and close this. What do you think?

**Comment by surchs** [comment]
@rmanaem: yeah, that's a great idea! Do you want to start spinning out these issues from the checkboxes in #2 and then add this to each of them? Then we can discuss more there.

**Comment by rmanaem** [comment]
Added this as a note to #2 and will also be added to each of the categorical variables' issue as a task
