### ISSUE TITLE
[BUG] Sex column in query output has `http://api.stardog.com/XXX` values that do not resolve to anything

### ISSUE THREAD

**Issue by Remi-Gau** [neurobagel/old-query-tool#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

For all rows for the Sex column of the output of a query to something meaningful.

### Current Behavior

When running a query (in this case the simplest query to return all participants / sessions) I get a giant participant-level-results.tsv.

Some of the values in the Sex column point to things like `http://api.stardog.com/9.796` which does not resolve to anything meaningful.

This concerns datasets:

Sex and Age columns are swapped: 

000119: https://github.com/OpenNeuroDatasets/ds000119/blob/master/participants.tsv
000121: https://github.com/OpenNeuroDatasets/ds000121/blob/master/participants.tsv
001510: https://github.com/OpenNeuroDatasets/ds001510/blob/master/participants.tsv
002242: https://github.com/OpenNeuroDatasets/ds002242/blob/master/participants.tsv
002655: https://github.com/OpenNeuroDatasets/ds002655/blob/master/participants.tsv
003606: https://github.com/OpenNeuroDatasets/ds003606/blob/master/participants.tsv

Sex coded as 1 and 0

003424: https://github.com/OpenNeuroDatasets/ds003424/blob/master/participants.tsv
003453: https://github.com/OpenNeuroDatasets/ds003453/blob/master/participants.tsv

Animal data (not sure what the cause could be)

004145: https://github.com/OpenNeuroDatasets/ds004145/blob/master/participants.tsv

### Error message

No error message

### How to reproduce

run the "default" query and check the TSV content

**Comment by surchs** [comment]
@alyssadai has some information about why this happens, we will look into how to prevent it from happening some other time

**Comment by surchs** [comment]
This is a data quality issue, tracking it here: https://github.com/neurobagel/planning/issues/67
