### ISSUE TITLE
[BUG] minimum age gets melted into node API in query

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I can run a query for a single node and define a minimum age

### Current Behavior

if I set sex, all is well: `https://federate.neurobagel.org/query/?&node_url=https://api.neurobagel.org/&sex=snomed:248153007`

if I set minimum age, this happens: `https://federate.neurobagel.org/query/?&node_url=https://api.neurobagel.org/min_age=1` 

### Error message

federation API rightly complains that 

`"Unrecognized Neurobagel node URL(s): ['https://api.neurobagel.org/min_age=1/']`

### Environment

- any single or multiple node selection except "All"

### How to reproduce

1. Select any node other than "All"
2. define a minimum age
3. watch it break with "Oops"

### Anything else?

see also https://github.com/OpenNeuroOrg/openneuro/issues/2807

most likely this is our culprit: 
https://github.com/neurobagel/query-tool/blob/dadbee332c593f95f5bab9bc037837f2241a6f76/components/QueryForm.vue#L222-L227

i.e. we do not concatenate `min_age` correctly. 

The reason this doesn't break for the "All" node is that we encode "All" as "no node parameter set":

`https://federate.neurobagel.org/query/?min_age=1`

so in this very specific case, `min_age` actually is the first query parameter and gets parsed correctly. This is most likely a leftover thing from when a query tool only ever talked directly to a node API and the federation API didn't exist yet.

**Comment by surchs** [comment]
Options we have here:
- [ ] be more smart about when we prefix a query parameter with `&`, i.e. only if it follows a previous parameter
- [ ] add `&` everytime. It's not "proper" but it is valid :shrug:

**Comment by rmanaem** [comment]
I wonder if there is a library we can use that allows us to pass params as an object something similar to `params` of `httpx.get` we use in federation-api.

**Comment by surchs** [comment]
you mean as part of a post body as opposed to the get we use here? Is that used somewhere else already?
For this specific bug, we need to make sure we only pass `min_age` without a leading `&` if we're certain that it is the first query parameter. This used to be always the case, but now the `node` query parameter can be before `min_age` whenever any node is selected except "All"
