### ISSUE TITLE
#334 broke e2e on main

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#342]
looks like https://github.com/neurobagel/query-tool/pull/334 fails e2e tests on main https://github.com/neurobagel/query-tool/actions/runs/7257195258/job/19770631514 after merge but didn't in the PR. I guess the PR branch was without conflict but not up to date with main? Not a huge deal but needs to be fixed right away because all other open PRs are now also failing: https://github.com/neurobagel/query-tool/pulls

@rmanaem mind taking a look since you merged #334?

**Comment by surchs** [comment]
Reading a little further, I believe that I was wrong about what state the tests are running in on a PR branch. From the docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request it seems that indeed the tests are run not on the PR branch itself, but on a (hypothetical ?) merge commit of the PR branch into the target (main) branch:

> Note that GITHUB_SHA for this event is the last merge commit of the pull request merge branch. If you want to get the commit ID for the last commit to the head branch of the pull request, use github.event.pull_request.head.sha instead.

So I understand even less how the tests could be passing in the PR but then fail immediately after the merge.

**Comment by rmanaem** [comment]
The issue was that I had updated repo variables to include the changes made in #337 and had forgotten to revert them.
It's fixed now see https://github.com/neurobagel/query-tool/actions/runs/7257195258/job/19795344279

**Comment by surchs** [comment]
So you had changed repo variables on the GitHub settings side between the PR being approved and you merging the PR? Just trying to understand how we went from "happy" PR to "sad" merge

**Comment by rmanaem** [comment]
Yes

**Comment by surchs** [comment]
OK, sounds good. Thanks for the explanation and the fix!
