### ISSUE TITLE
Update dropdown options

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#37]
Update the options in `CategoricalOptions` in `index.vue` once the data has been added to graph.

**Comment by rmanaem** [comment]
Blocked by data to be added to the graph.

**Comment by surchs** [comment]
Could you reference the issue this is blocked by @rmanaem? Afaik we have all requirred data in the test instance, but not all possible values for things like diagnosis etc.

**Comment by rmanaem** [comment]
@surchs I'm not sure which issue it is or if even there is an issue for it. 
However, since everything for options (all possible values) of categorical fields (diagnosis, assessment, modality, ...) is hardcoded, I need to run a query to get them and update the `CategoricalOptions` in `index.vue` ([see here](https://github.com/neurobagel/query-tool/issues/2#issuecomment-1410877253)). That can't be done using the test instance and has to wait for the latest data ( I think QPN and PPMI) to be in the graph.

**Comment by surchs** [comment]
I see. Yes, that's true. We'll have to run a query once we have our real data in the graph to populate these choices.

**Comment by rmanaem** [comment]
@surchs I couldn't find anything on `http://neurobagel.org/vocab/cogAtlas-1234` after running [this query](https://github.com/neurobagel/query-tool/issues/2#issuecomment-1410877253) which gives us [query_sparql_results.csv](https://github.com/neurobagel/query-tool/files/11225136/the_big_optional_query_sparql_results.csv) for the available options.  Do you know where/how I can get the human-readable label for this?

Also, I noticed we don't have `cogAtlas` as a prefix in the `query_template` in the API. Perhaps a small issue and fix after merging this?

**Comment by surchs** [comment]
Yes, exactly. 

- Human labels: https://github.com/neurobagel/project/issues/47 (in backlog atm)
- cogAtlas prefix: https://github.com/neurobagel/bagel-cli/issues/106 (also backlog atm)

So yeah, I think we might have to wait on that.

**Comment by rmanaem** [comment]
Once https://github.com/neurobagel/encarta/issues/10 is done, the terms and their references need to be updated to correspond to the new schema!
