### ISSUE TITLE
Refactor before deployment

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#40]
- [x] Go through existing props
  - Set them to required if the component doesn't work without them
  - or provide a sensible default for them
- [x] Change `Cohort Definition Tool` to `Query Tool` in `index.vue`
- [x] Rename `Modality` to `Imagin modality`
- [x] Rename `updateCategoricalField` method in `CategoricalField.vue` to `updateField`
- [x] ~Add bagel favicon~
- [x] Update the modality colors
- [x] ~Update README.md to follow the same pattern as the api~
- [x] ~Add loading animation while the result is being retrieved~

**Comment by surchs** [comment]
ping @alyssadai / @jarmoza for drafts and ideas for the favicon?

**Comment by rmanaem** [comment]
I already pinged them on slack channel.
