### ISSUE TITLE
add basic user documentation on how to do a query

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#5]
A user should be able to check out some basic instructions and screenshots to get a sense of:

- what can this thing do?
- how do I create and run a query?
- where should I direct my feedback / questions?

This could live in our docs https://www.neurobagel.org/documentation/ or in a README

**Comment by surchs** [comment]
@rmanaem did we say that you are tackling this issue as part of the individual UI element issues in the milestone?

**Comment by rmanaem** [comment]
Yea, I think it's been amended to the #2 and as a sub-task to each issue in its task list. I'll close this.
