### ISSUE TITLE
Modify tool for new subject level results

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#76]
To implement the functionality for specs outlined [here](https://github.com/neurobagel/documentation/wiki/Query-Tool):

- [x] Implement a check box to switch between the two `.csv` files
- [x] Modify `generateCSVString` to return new subject-level results (the two `.csv` files).
- [x] Update `DownloadResultsButton` component test
- [x] Update README.md to mention what the tool now returns based on the status of the checkbox

As part of this, we need to make sure that we return the human-readable labels to the users, not the IRI for diagnosis levels and sex. See https://github.com/neurobagel/project/issues/47

For the moment, we will use the hard-coded mapping of controlled term IRI to human-readable label that already exists in the query tool

**Comment by surchs** [comment]
Blocked by https://github.com/neurobagel/api/issues/112

**Comment by rmanaem** [comment]
Unlocked by https://github.com/neurobagel/api/pull/125

**Comment by surchs** [comment]
> Unlocked by [neurobagel/api#125](https://github.com/neurobagel/api/pull/125)

:tada: 
but also: this feels like bot work. Can it be bot work?
