### ISSUE TITLE
Query for 0 sessions throws an error

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#95]
When a query with the value 0 for minimum number of session is submitted, the query tool throws a generic error. The error is generated by API see [here](https://github.com/neurobagel/api/blob/f891ff0860589e9fa5590d092d220934ae395597/app/api/models.py#LL18C54-L18C54).

**Comment by surchs** [comment]
I think the query tool shouldn't allow queries that the API thinks are malformatted. Having said that: we should also have a brief chat on whether querying for 0 sessions might actually make sense for when I want people who actually have **no** imaging sessions.

Just a thought dump, not for this issue
